version: '3.1'

networks:
  proxy_default:
    external: true

services:

  ui:
    image: dina/dnakey:v1.0
    environment:
      - VIRTUAL_HOST=local-dnakey.nrm.se
      - VIRTUAL_PORT=8080
    volumes:
      - ./project-initdata.yml:/usr/src/myapp/project-initdata.yml
      - ./logs/dnakey.log:/usr/src/myapp/logs/dnakey.log
    external_links:
      - solr:solr
    networks:
      - proxy_default
