version: '3.1'

services:

  ui:
    image: dina/dnakey:v1.0
    environment:
      - VIRTUAL_HOST=beta.dnakey.se
      - VIRTUAL_PORT=8080
    volumes:
      - ./project-initdata.yml:/usr/src/myapp/project-initdata.yml
    extra_hosts:
      - "solr.nrm.se:193.10.57.89"


# running with external proxy (check the network 'docker network ls')
networks:
  default:
    external:
      name: dwproxy_default
