version: '3.1'

services:

  ui:
    image: dina/dnakey:v0.3
    environment:
      - VIRTUAL_HOST=beta.dnakey.se
      - VIRTUAL_PORT=8080
    volumes:
      - ./project-initdata.yml:/usr/src/myapp/project-initdata.yml
    extra_hosts:
      - "dina-db.nrm.se:172.16.0.86"


# running with external proxy (check the network 'docker network ls')
networks:
  default:
    external:
      name: dwproxy_default
