version: '3.1'

services:

  ui:
    image: dina/dnakey:v0.2
    environment:
      - VIRTUAL_HOST=beta.dnakey.se
      - VIRTUAL_PORT=8080
    extra_hosts:
      - "dina-db.nrm.se:172.16.0.86"

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

