version: '3.1'

services:

  ui:
    image: dina/dnakey:v0.3
    environment:
      - VIRTUAL_HOST=local-dnakey.nrm.se
      - VIRTUAL_PORT=8080
    volumes:
      - ./project-initdata-local.yml:/usr/src/myapp/project-initdata.yml
    # extra_hosts:
    #   - "dina-db.nrm.se:172.16.0.86"

# networks:
#   default:
#     external:
#       name: dwproxy_default

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

