version: '3.1'

services:   
  
  ui:
    image: dina/dnakey:v0.1 
    environment:
      - VIRTUAL_HOST=beta.dnakey.se
      - VIRTUAL_PORT=8080
#    volumes:
#      - ./data/dnakey/geo_coords.tsv:/usr/geo_coords.tsv
#      - ./data/blast/db:/usr/local/blast/db
#      - ./data/blast/tempfastafiles:/usr/local/blast/tempfastafiles
#    ports:
#      - "8080:8080"
    extra_hosts:
      - "dina-db.nrm.se:172.16.0.86"
 
#      - "8443:8443"
#      - "9443:443"
#      - "9990:9990"

 


# running with external proxy (check the network 'docker network ls')
networks:
  default:
    external:
      name: dwproxy_default